/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Laurie' at '11/09/15 11:06' with Gradle 2.6
 *
 * @author Laurie, @date 11/09/15 11:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
